// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	operations "github.com/asardak/arrival-time-service/pkg/predict-service/client/operations"
	mock "github.com/stretchr/testify/mock"
)

// PredictServiceClient is an autogenerated mock type for the PredictServiceClient type
type PredictServiceClient struct {
	mock.Mock
}

// Predict provides a mock function with given fields: params
func (_m *PredictServiceClient) Predict(params *operations.PredictParams) (*operations.PredictOK, error) {
	ret := _m.Called(params)

	var r0 *operations.PredictOK
	if rf, ok := ret.Get(0).(func(*operations.PredictParams) *operations.PredictOK); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PredictOK)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*operations.PredictParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
