// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/asardak/arrival-time-service/internal/app"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindRoute provides a mock function with given fields: ctx, point
func (_m *Repository) FindRoute(ctx context.Context, point app.Point) (app.Route, error) {
	ret := _m.Called(ctx, point)

	var r0 app.Route
	if rf, ok := ret.Get(0).(func(context.Context, app.Point) app.Route); ok {
		r0 = rf(ctx, point)
	} else {
		r0 = ret.Get(0).(app.Route)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, app.Point) error); ok {
		r1 = rf(ctx, point)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveRoute provides a mock function with given fields: ctx, route
func (_m *Repository) SaveRoute(ctx context.Context, route app.Route) error {
	ret := _m.Called(ctx, route)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, app.Route) error); ok {
		r0 = rf(ctx, route)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
